---
layout: page-menu
title: Debezium at Commonhaus FAQ
permalink: /foundation/faq/
---
:linkattrs:
:icons: font
:source-highlighter: highlight.js

=== Why move to a foundation?

Enable us to welcome more contributions from a diverse range of developers and organisations.

=== Which Debezium projects as moving to a foundation?

All projects under the https://github.com/debezium[Debezium GitHub] organization.

=== What is Commonhaus?

See https://www.commonhaus.org[https://www.commonhaus.org].

=== Why Commonhaus?

The main reason for choosing Commonhaus over another foundation was its governance framework, which emphasises project self-governance.
See, in particular, its guiding principles.

=== Why not move to any other foundation?

See Commonhaus’ own https://www.commonhaus.org/about/faq.html[FAQ].

=== What does the move consist of exactly?

The move consists of donating the Debezium-related intellectual property owned by Red Hat.
The donated intellectual property includes in particular:

* Debezium trademark
* All related domain names

This does not include copyright, since Red Hat does not have exclusive claims to copyright on the Debezium code.

=== Is Red Hat reducing the funding for Debezium development?

No, not all.

=== How is Red Hat's involvement in Debezium changing?

Red Hat's involvement in Debezium remains unchanged and as committed as ever.

The Debezium team is expecting increased collaboration between Red Hat and other organizations, which may require setting time aside to onboard new contributors and collaborators.

=== What is changing in practice for contributors to the Debezium project?

Commonhaus requires Debezium to adhere to its https://www.commonhaus.org/policies/[policies], including in particular its https://www.commonhaus.org/policies/ip-policy/[intellectual property policy], and https://www.commonhaus.org/policies/trademark-policy/[trademark policy].

This is great news for you all, as it legally binds the project to remain open-source forever.
Commonhaus also requires having a code of conduct, and provides a recommended one, but each project can freely customize the details as needed.

Debezium contributors can opt to become Commonhaus Members; this is not a requirement to participate in the Debezium project, but is a requirement to help define Commonhaus.

The Debezium project's core contributors, internal governance and processes remain the same.