---
layout: post
title:  Debezium 3.0.1.Final Released
date:   2024-10-28
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

I am pleased to announce the first maintenance release for the Debezium 3 release stream, **3.0.1.Final**.
This maintenance release introduces several new features including support for Cassandra 5, PostgreSQL 17, and MySQL 9.1.
In addition, there are some configuration improvements with Debezium Server supporting YAML.

+++<!-- more -->+++

[id="breaking-changes"]
== Breaking changes

We announced the discontinuation of publishing Debezium container images to Docker Hub link:2024-09-18-quay-io-reminder.adoc[here] and that they are now solely available on https://quay.io[quay.io] (https://issues.redhat.com/browse/DBZ-8327[DBZ-8327]).
Please be sure to update your container pipelines to continue to use the most up-to-date images.

[id="new-features-and-improvements"]
== New features and improvements

Debezium 3.0.1.Final introduces a couple of improvements and features, lets take a look at each individually.

=== Cassandra 5 support

The Apache Cassandra Community released Cassandra 5 in September 2024, and we are happy to report that Debezium is now compatible and supports the latest major milestone of Cassandra (https://issues.redhat.com/browse/DBZ-8347[DBZ-8347]).

A new Debezium connector artifact is now available for Cassandra 5:
[source,xml]
----
<dependency>
    <groupId>io.debezium</groupId>
    <artifactId>debezium-connector-cassandra-5</artifactId>
    <version>3.0.1.Final</version>
</dependency>
----

In addition, the new Cassandra 5 connector is included with Debezium Server.

=== MySQL 9.1 support

Oracle released MySQL 9.1 just a short weeks ago, and we're happy to also report that Debezium now supports MySQL 9.1 (https://issues.redhat.com/browse/DBZ-8324[DBZ-8424]).
This update also includes an update to the MySQL JDBC driver version _9.1.0_.

For existing users, this should require no additional changes.

=== PostgreSQL 17 support

The PostgreSQL team released the latest PostgreSQL 17 database at the end of September 2024, and we're happy to report that Debezium officially supports PostgreSQL 17 (https://issues.redhat.com/browse/DBZ-8275[DBZ-8275]).
For any existing users, this update should require no additional changes.

=== Using YAML with Debezium Server

Debezium Server is a standalone environment for running Debezium connectors outside of a Kafka Connect environment on bare metal, VMs, or Kubernetes.
Debezium Server users are familiar with the configuration property file called `application.properties`, where you supply the source and sink connector configurations to define your Debezium Server pipeline.

We are excited to share that we've added support for YAML when using Debezium Server, allowing you to now define your configuration in `application.yml` (https://issues.redhat.com/browse/DBZ-8313[DBZ-8313]).
Please review the Quarkus documentation on using YAML configuration should you have any questions.

[id="other-fixes"]
== Other fixes

In total there were https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.0.1.Final)[35 issues] resolved in Debezium 3.0.1.Final.
The list of changes can also be found in our https://debezium.io/releases/3.0[release notes].

Here are some noteworthy changes:

* Oracle DDL parsing will fail if the DDL ends with a new line character https://issues.redhat.com/browse/DBZ-7040[DBZ-7040]
* Missing documentation for MongoDb SSL configuration https://issues.redhat.com/browse/DBZ-7927[DBZ-7927]
* Conditionalization implemented for single-sourcing MySQL/MariaDB content isn't working as expected https://issues.redhat.com/browse/DBZ-8094[DBZ-8094]
* Support batch write to AWS Kinesis https://issues.redhat.com/browse/DBZ-8193[DBZ-8193]
* Debezium is replaying all events from an older offset https://issues.redhat.com/browse/DBZ-8194[DBZ-8194]
* Embedded MySqlConnector "Unable to find minimal snapshot lock mode" since 2.5.4.Final https://issues.redhat.com/browse/DBZ-8271[DBZ-8271]
* Reselect Post Processor not working when pkey of type uuid etc. https://issues.redhat.com/browse/DBZ-8277[DBZ-8277]
* BinlogStreamingChangeEventSource totalRecordCounter is never updated https://issues.redhat.com/browse/DBZ-8290[DBZ-8290]
* Restart Oracle connector when ORA-01001 invalid cursor exception is thrown https://issues.redhat.com/browse/DBZ-8292[DBZ-8292]
* Connector uses incorrect partition names when creating offsets https://issues.redhat.com/browse/DBZ-8298[DBZ-8298]
* ReselectPostProcessor fails when reselecting columns from Oracle https://issues.redhat.com/browse/DBZ-8304[DBZ-8304]
* Debezium MySQL DDL parser: SECONDARY_ENGINE=RAPID does not support https://issues.redhat.com/browse/DBZ-8305[DBZ-8305]
* SQL Server Documentation for CDC on Server table https://issues.redhat.com/browse/DBZ-8314[DBZ-8314]
* Oracle DDL failure - subpartition list clause does not support in-memory clause https://issues.redhat.com/browse/DBZ-8315[DBZ-8315]
* DDL statement couldn't be parsed https://issues.redhat.com/browse/DBZ-8316[DBZ-8316]
* Binary Log Client doesn't process the TRANSACTION_ PAYLOAD header https://issues.redhat.com/browse/DBZ-8340[DBZ-8340]
* Oracle connector: archive.log.only.mode stop working after reach SYSDATE SCN https://issues.redhat.com/browse/DBZ-8345[DBZ-8345]

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/ani-sha[Anisha Mohanty],
Kunal Bhatnagar,
https://github.com/Naros[Chris Cranford],
https://github.com/dongwook-chan[Dongwook Chan],
https://github.com/x-0-r[Franz Emberger],
https://github.com/gaurav7261[Gaurav Miglani],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/dargmuesli[Jonas Thelemann],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/nathan-smit-1[Nathan Smit],
https://github.com/obabec[Ondrej Babec],
https://github.com/zikphil[Philippe Labat],
https://github.com/roldanbob[Robert Roldan],
https://github.com/smiklosovic[Stefan Miklosovic], and
https://github.com/vjuranek[Vojtech Juranek]!