---
layout: post
title:  Moving Debezium to a Foundation
date:   2024-11-04 00:00:00
tags: [ announcement ]
author: ccranfor
---

After consulting with the community both inside and outside of Red Hat, we have made the decision to submit a request for the https://github.com/debezium[Debezium project] to join the https://www.commonhaus.org[Commonhaus Foundation].

+++<!-- more -->+++

Today, we are thrilled to announce that the Debezium project is starting the transition to the Commonhaus Foundation.
Debezium is the leading open-source distributed platform for Change Data Capture (CDC), and has been sponsored exclusively by Red Hat since its inception back in 2015.
The move to CommonHaus aligns with our link:2024-10-03-plan-to-move-debezium-to-foundation[goal to foster a more inclusive, collaborative environment].

== Why Move to a Foundation?

Debezium has seen exceptional growth and adoption since 2015.
Many data streaming providers rely on a variety of foundational components, and for CDC, that most often means Debezium.
We want to continue this momentum, and we believe moving to a foundation helps to facilitate that goal.

For more details, see our link:2024-10-03-plan-to-move-debezium-to-foundation[goals and reasons] for moving to a foundation.

== Why Commonhaus?

Commonhaus stands out because of its innovative governance framework and commitment to project independence.
This benefits the Debezium community and its collaborators by allowing us to continue to provide the same release cadence and commitment to excellence that we have today.
We are thrilled to join other prominent projects at Commonhaus, which includes Hibernate, Jackson, and Quarkus.

== What's Next?

We are committed to keeping Debezium the open-source leader in the Change Data Capture (CDC) space.
We remain ever vigilant in our pursuit to innovate, evolve, and deliver the best experience for our vibrant user community.
This transition will enable us to welcome a wider array of contributions from a more diverse cross-section of developers and organizations.

The move to foundation isn't just about Debezium, it's equally about the community.
If you're organization wishes to ensure that Debezium evolves and grows in a direction that benefits your organization, get involved.
Join us in helping Debezium transition to the Commonhaus Foundation.

The Commonhaus Foundation is currently bootstrapping, enabling it to be shaped to help you and open-source projects like Debezium have a place to call home.
For questions about this move, please refer to our link:/foundation/faq[dedicated FAQ] or reach out through our usual channels.

On behalf of the Debezium team.
